package DependencyParser;

public enum UniversalDependencyType {
    ACL, ADVCL, ADVMOD, AMOD, APPOS, AUX, CASE, CC, CCOMP, CLF, COMPOUND, CONJ, COP, CSUBJ, DEP, DET, DISCOURSE,
    DISLOCATED, EXPL, FIXED, FLAT, GOESWITH, IOBJ, LIST, MARK, NMOD, NSUBJ, NUMMOD, OBJ, OBL, ORPHAN, PARATAXIS,
    PUNCT, REPARANDUM, ROOT, VOCATIVE, XCOMP
}
